spring.application.name=ai-job-matching


spring.datasource.url=jdbc:postgresql://localhost:5434/ai_job_matching
spring.datasource.username=ai_user
spring.datasource.password=ai_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true